name: daynotes

services:
  daynotes.sgbd:
    build:
      context: ./daynotes.sgbd/
      dockerfile: Dockerfile
    container_name: daynotes.sgbd
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      - dbNet

  daynotes.api:
    build:
      context: ./daynotes.api/
      dockerfile: Dockerfile
      args:
        uid: ${UID:-1000}
    container_name: daynotes.api
    environment:
      - APACHE_RUN_USER=#${UID:-1000}
      - APACHE_RUN_GROUP=#${UID:-1000}
      - SSL_ENABLED=${SSL_ENABLED}
      - DOMAIN=${DOMAIN}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
      - TZ=Europe/Paris
    volumes:
      - ./daynotes.api/web:/var/www/html
      - laravel_storage:/var/www/html/storage/app/public
      - ./daynotes.api/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./daynotes.api/ports.conf:/etc/apache2/ports.conf
      - letsencrypt_certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      sgbd:
        condition: service_healthy
      certbot:
        condition: service_completed_successfully
    restart: always
    entrypoint: sh -c "/var/www/html/onLaunch.sh && apache2-foreground"
    networks:
      - internet
      - dbNet

  daynotes.listener:
    build:
      context: ./daynotes.listener/
      dockerfile: Dockerfile
      args:
        uid: ${UID:-1000}
    container_name: daynotes.listener
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./daynotes.api/web:/var/www/html
    depends_on:
      sgbd:
        condition: service_healthy
    restart: always
    networks:
      - dbNet

networks:
  internet:
    driver: bridge
  dbNet:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  laravel_storage:
    driver: local
  letsencrypt_certs:
    driver: local